# Generated by Django 2.1.3 on 2018-11-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saledetail',
            old_name='num_items',
            new_name='quantity',
        ),
    ]
