# Generated by Django 2.1.3 on 2018-12-02 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20181202_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saledetail',
            old_name='product',
            new_name='sale',
        ),
        migrations.AddField(
            model_name='saledetail',
            name='prouct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='store.Product'),
        ),
    ]
